### PR TITLE
added Tracer exposure to adapters

### PR DESCRIPTION
**Pull request by LutzLange**
I need the Tracer to better work with OpenTracing and to be able to connect the go-sensor to OpenTracing GRPC tracing. Please merge.

### CODE REVIEW

**Comment by steveww** [comment]
Alternatively set the Opentracing Global Tracer in NewSensor("foo").

InitGlobalTracer(s.tracer)

**Comment by steveww** [comment]
The context contains the parent span that has a Tracer() function to get the tracer.
Not sure this PR is required.
Admittedly the docs could be better.

**Comment by steveww** [comment]
Inside a wrapped handler.

parent := ctx.Value("parentSpan").(ot.Span)
tracer := parent.Tracer()

**Comment by pglombardo** [comment]
@LutzLange does this resolve your issue?  I'll close this PR.

**Pull request closed without merging**
