### PR TITLE
HTTP HandleFunc / HTTP client tracing simplified

### PR DESCRIPTION
**Pull request by noctarius**
Created a simplified way (wrapper / adapter) to handle simple cases like HTTP server handler or HTTP client requests. Other possibilities like SQL, MQ or other things could follow.

### CODE REVIEW

**Comment by noctarius** [comment]
PR builder fails due to the fact it tries to resolve _github.com/instana/golang-sensor_ from the current master instead from the commit :(

**Comment by pglombardo** [comment]
Thanks @noctarius! Can you add some documentation on how to use these?  Maybe on the front README and I'll copy/paste into a docs PR.

**Comment by noctarius** [comment]
done :)

**Comment by steveww** [comment]
There is a neater way IMHO to do the handler wrappers, see https://github.com/steveww/go-appd

The wrappers are at the end of appd.go

**Comment by noctarius** [comment]
added :)

**Comment by steveww** [comment]
Much neater :-)

**Comment by noctarius** [comment]
Screen Shot 2019-03-22 at 15 23 12
fixed it :)

**Comment by pglombardo** [comment]
Yay I'll test soon and merge - thanks!

**Comment by pglombardo** [comment]
Tested & looks great.  Thanks @noctarius & @steveww!

**Pull request merged**
